# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170821_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('period_of_work', models.CharField(max_length=500)),
                ('bid_opening_date', models.CharField(max_length=500)),
                ('bid_closing_date', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
